<?php
/**
 * BOSA Statement module.
 *
 * Generate a statement based on the users chosen dates.
 *
 * @author Thomas Thune Hansen <tth@bellcom.dk>
 * @copyright bellcom open source aps
 */


/**
 * Implements hook_menu()
 */
function bosa_statement_menu(){
  $items = array();

  $items['admin/bosa/statement'] = array(
    'title' => 'BOSA Statement',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bosa_statement_form'),
    'access callback' => 'bosa_statement_access',
    'access arguments' => array(1),
  );

  return $items;
}

/**
 * Implements hook_permission()
 */
function bosa_statement_permission(){
  return array(
    'bosa full statement' => array(
      'title' => t('BOSA See full statement'),
      'description' => t('See statement for all users'),
    ),
  );
}

/**
 * Access callback for menu item
 */
function bosa_statement_access($arg){
  global $user;

  // If the user tries to see his or her own statement.
  if($arg == $user->uid){
    return TRUE;
  }

  // If the user is allowed to see full statement.
  if(user_access('bosa full statement')){
    return TRUE;
  }

  // Otherwise go away.
  return FALSE;
}

/**
 * Statement form
 */
function bosa_statement_form($form, $form_state){
  if(isset($form_state['values'])){
    // Generate table contents if the form has been submitted.
    $from = $form_state['values']['date_from'];
    $to = $form_state['values']['date_to'];

    $cancel = $form_state['values']['show_cancelled'];

    $uid = FALSE;

    // Format dates
    $from = $from['year'] . '-' . str_pad($from['month'], 2, 0, STR_PAD_LEFT) . '-' . str_pad($from['day'], 2, 0, STR_PAD_LEFT) . ' 00:00:01';
    $to = $to['year'] . '-' . str_pad($to['month'], 2, 0, STR_PAD_LEFT) . '-' . str_pad($to['day'], 2, 0, STR_PAD_LEFT) . ' 23:59:59';

    if( (int)arg(3) ){
      $uid = (int) arg(3);
    }

    $statement = bosa_statement_get_statement($from, $to, $cancel, $uid);

    // If the user clicked download, send a file.
    if($form_state['clicked_button']['#parents'][0] == 'csv'){
      bosa_statement_get_csv($statement);
    }

    if($form_state['clicked_button']['#parents'][0] == 'xls'){
      bosa_statement_get_xls($statement);
    }
  }

  // Table header.
  $header = array(
    'Ordrenr.',
    'Ordredato',
    'Kundenavn/adr',
    'Produkttitel',
    'Endhedspris',
    'Mængde / antal personer',
    'I alt omsætning',
    'Aflyst'
  );

  $form['date_from'] = array(
    '#title' => t('Fra'),
    '#type' => 'date',
    '#default_value' => NULL
  );

  $form['date_to'] = array(
    '#title' => t('Til'),
    '#type' => 'date',
  );

  $form['show_cancelled'] = array(
    '#title' => t('Vis aflyste aktiviteter'),
    '#type' => 'checkbox',
  );

  $form['submit'] = array(
    '#value' => t('Vis'),
    '#type' => 'submit',
  );

  // Only show the download button, if a search is made.
  if(isset($form_state['values'])){
    $form['csv'] = array(
      '#value' => t('Download CSV'),
      '#type' => 'submit',
    );

    $form['xls'] = array(
      '#value' => t('Download XLS'),
      '#type' => 'submit',
    );

  }

  $form['statement'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $statement,
    '#empty' => 'Opdater søgekriterier',
  );

  return $form;
}

/**
 * implements hook_form_submit()
 */
function bosa_statement_form_submit($form, &$form_state){
  // Rebuild form on submit.
  $form_state['rebuild'] = TRUE;

}

/**
 * Generate statement array
 *
 * Statement is generated for based upon the
 * dates of the products. Each line should show a line item
 * with the wanted info.
 */
function bosa_statement_get_statement($from, $to, $cancel = FALSE, $uid = FALSE){
  $grand_total_cancelled = 0;
  $grand_total;

  $sql = 'SELECT `entity_id`
    FROM  `field_data_field_offer_dato`
    WHERE `field_offer_dato_value` >= :from
    AND `field_offer_dato_value` <= :to';

  $params = array(':from' => $from, ':to' => $to);

  // If a uid is sent, only show the users products.
  if($uid){
  $sql = 'SELECT `entity_id`
    FROM  `field_data_field_offer_dato`
    LEFT JOIN `commerce_product` ON
      `commerce_product`.`product_id` = `field_data_field_offer_dato`.`entity_id`
    WHERE `field_offer_dato_value` >= :from
    AND `field_offer_dato_value` <= :to
    AND `commerce_product`.`uid` = :uid';

    $params[':uid'] = $uid;
  }

  $query = db_query($sql, $params);

  $result = $query->fetchAll();

  if(empty($result)){
    return array(array('Ingen resultater'));
  }

  foreach($result as $dbrow){
    $product_ids[] = $dbrow->entity_id;
  }

  // Use entityfieldquery to fetch lineitems
  // for all products.
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'commerce_line_item', '=')
        ->fieldCondition('commerce_product', 'product_id', $product_ids, 'IN');

  $line_item_ids = array_keys( array_shift( $query->execute() ) );

  $line_items = commerce_line_item_load_multiple($line_item_ids);

  // The statement shows a row per lineitem.
  foreach($line_items as $line_item){
    try {
      $product_id = $line_item->commerce_product[LANGUAGE_NONE][0]['product_id'];

      $product = commerce_product_load($product_id);

      $product_title = '<a href="/admin/commerce/products/'. $product->product_id .'">' . $product->title . '</a>';

      $commerce_order = commerce_order_load($line_item->order_id);
      // Since this is used for accounting we only show completed
      // orders.
      if($commerce_order->status == "completed"){
        $profile_id = $commerce_order->commerce_customer_billing[LANGUAGE_NONE][0]['profile_id'];

        $customer_profile = commerce_customer_profile_load($profile_id);
        // Generate customer information
        $customer_address_line = $customer_profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'] . '<br>'
                               . $customer_profile->commerce_customer_address[LANGUAGE_NONE][0]['thoroughfare'] . '<br>'
                               . $customer_profile->commerce_customer_address[LANGUAGE_NONE][0]['postal_code'] . ' '
                               . $customer_profile->commerce_customer_address[LANGUAGE_NONE][0]['locality'] . '<br>'
                               . $customer_profile->commerce_customer_address[LANGUAGE_NONE][0]['country'];

        // Generate price information
        $price = commerce_currency_amount_to_decimal(
                          $line_item->commerce_unit_price[LANGUAGE_NONE][0]['amount'],
                          $line_item->commerce_unit_price[LANGUAGE_NONE][0]['currency_code']
                        );

        $price_total = $price * $line_item->quantity;

        $grand_total += $price_total;

        // Populate row array
        $row[] = array(
          $line_item->order_id,
          date('d/m/Y', $commerce_order->created),
          $customer_address_line,
          $product_title,
          $price,
          (int)$line_item->quantity,
          $price_total,
          ''
        );

      }
    }
    // Pokemon!
    catch(Exception $e){
    }
  }

  // Add cancellation info.
  // Cancellation info i fetched from bosa_reservation
  // module.
  if($cancel){
    foreach($product_ids as $product_id){
      $all_info = bosa_reservation_get_info($product_id);

      if(!empty($all_info)){
        // There is a row for each product referencing an order.
        // Not 2 but 1. So info abount multiple lineitems are stored
        // on the same row. In the end, what we show here become pseudo
        // lineitems.
        foreach($all_info as $info){
          $refund_info = unserialize($info->data);

          // And because of this, we need to calculate the quantities.
          $second_price_quantity = 0;
          if(isset($refund_info['2nd_price'])){
            $second_price_quantity = $refund_info['2nd_price'];
          }

          $quantity = $refund_info['quantity'] - $second_price_quantity;

          $product = commerce_product_load($product_id);

          $price = commerce_currency_amount_to_decimal($product->commerce_price[LANGUAGE_NONE][0]['amount'], 'DKK');
          $second_price = commerce_currency_amount_to_decimal($product->field_2nd_price[LANGUAGE_NONE][0]['amount'], 'DKK');

          $product_title = '<a href="/admin/commerce/products/'. $product->product_id .'">' . $product->title . '</a>';

          $commerce_order = commerce_order_load($info->order_id);

          $profile_id = $commerce_order->commerce_customer_billing[LANGUAGE_NONE][0]['profile_id'];

          $customer_profile = commerce_customer_profile_load($profile_id);
          // Generate customer information
          $customer_address_line = $customer_profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'] . '<br>'
                                . $customer_profile->commerce_customer_address[LANGUAGE_NONE][0]['thoroughfare'] . '<br>'
                                . $customer_profile->commerce_customer_address[LANGUAGE_NONE][0]['postal_code'] . ' '
                                . $customer_profile->commerce_customer_address[LANGUAGE_NONE][0]['locality'] . '<br>'
                                . $customer_profile->commerce_customer_address[LANGUAGE_NONE][0]['country'];

          $total_cancelled_format = $price * $quantity;

          $row[] = array(
              $info->order_id,
              date('d/m/Y', $commerce_order->created),
              $customer_address_line,
              $product_title,
              $price,
              $quantity,
              '',
              $total_cancelled_format,
            );

          // In order to be consistent in the table view we set an extra row
          // with info about the 2nd prices items.
          // Yes! Great place to start being consistent...
          if($second_price_quantity){

            $total_second_cancelled_format = $second_price * $second_price_quantity;
            $row[] = array(
                '2nd' . $info->order_id,
                date('d/m/Y', $commerce_order->created),
                $customer_address_line,
                $product_title,
                $second_price,
                $second_price_quantity,
                '',
                $total_second_cancelled_format,
              );
              // Calculate grand total for last row.
              $grand_total_cancelled += $total_second_cancelled_format;
          }

        }
        // Calculate grand total for last row.
        $grand_total_cancelled += $total_cancelled_format;
      }
    }
  }

  // Bottom row, with grand total.
  $row[] = array('', '', '', '', '', '',  $grand_total, $grand_total_cancelled);
  return $row;
}

function bosa_statement_clean_statement($statement){
   // The statement we get, is intended for rendering as HTML,
  // so we need to clean up the tags, to make it presentable
  // in CSV.
  foreach ($statement as $value){
    $row = array();
    foreach($value as $column){
      $row[] = strip_tags($column);
    }

    $rows[] = $row;
  }

  return $rows;
}

/**
 * Generate CSV from statement, send it for download
 */
function bosa_statement_get_csv($statement){
  $rows = bosa_statement_clean_statement($statement);

  $filename = 'file.csv';
  header( "Content-Type: text/csv;charset=utf-8" );
  header( "Content-Disposition: attachment;filename=\"$filename\"" );
  header("Pragma: no-cache");
  header("Expires: 0");

  $fp = fopen('php://output', 'w');
  foreach ($rows as $fields){
    fputcsv($fp, $fields);
  }
  die(fclose($fp));
}

/**
 * Generate EXCEL spreadsheet from statement
 */
function bosa_statement_get_xls($statement){
  $rows = bosa_statement_clean_statement($statement);

  // PHPEccel library
  include 'libraries/PHPExcel/Classes/PHPExcel.php';
  include 'libraries/PHPExcel/Classes/PHPExcel/Writer/Excel2007.php';

  // Create new PHPExcel object
  $objPHPExcel = new PHPExcel();

  // Add some data
  $objPHPExcel->setActiveSheetIndex(0);

  foreach($rows as $r_id => $row){
    foreach($row as $c_id => $column){
      // Convert column array key to numeric for use in
      // spreadsheet.
      $c_id_alpha = strtr($c_id, "0123456789", "ABCDEFGHIJ");

      // Save column data to cell
      $objPHPExcel->getActiveSheet()->SetCellValue($c_id_alpha.($r_id+1), $column);
    }
  }

  $file = variable_get('file_temporary_path') . '/bosa_statement.xls';

  // Save Excel 2007 file
  $objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
  $objWriter->save($file);

  $file_name = basename($file);

  header("Content-Type: application/vnd.ms-excel");
  header("Content-Disposition: attachment; filename=$file_name");
  header("Content-Length: " . filesize($file));
  die(readfile($file));
}
